// Generated by CoffeeScript 1.6.3
(function() {
  var Url, should;

  should = require('should');

  Url = require('../lib/Url');

  describe('Url', function() {
    describe('#urlencode()', function() {
      return it('should return encoded strings like in PHP', function() {
        Url.urlencode('Kevin van Zonneveld!').should.be.equal('Kevin+van+Zonneveld%21');
        return Url.urlencode('http://kevin.vanzonneveld.net/').should.be.equal('http%3A%2F%2Fkevin.vanzonneveld.net%2F');
      });
    });
    return describe('#buildQuery()', function() {
      return it('should return prepared params like from http_build_query in PHP', function() {
        return Url.buildQuery({
          foo: 'bar',
          php: 'hypertext processor',
          baz: 'boom',
          cow: 'milk'
        }).should.be.equal('foo=bar&php=hypertext+processor&baz=boom&cow=milk');
      });
    });
  });

}).call(this);
