// Generated by CoffeeScript 1.6.3
(function() {
  var Validators, should;

  should = require('should');

  Validators = require('../lib/Validators');

  describe('Validators', function() {
    return describe('#companyIdentification()', function() {
      it('should return true', function() {
        Validators.companyIdentification('69663963').should.be["true"];
        Validators.companyIdentification('   69663963   ').should.be["true"];
        Validators.companyIdentification(69663963).should.be["true"];
        return Validators.companyIdentification(25596641).should.be["true"];
      });
      return it('should return false', function() {
        Validators.companyIdentification('---').should.be["false"];
        return Validators.companyIdentification('12345678').should.be["false"];
      });
    });
  });

}).call(this);
