// Generated by CoffeeScript 1.6.3
(function() {
  var Ares, ares, expect;

  expect = require('chai').expect;

  Ares = require('../../lib/Ares');

  ares = new Ares;

  describe('Ares', function() {
    return describe('#findByIdentification()', function() {
      it('should load old information about author', function(done) {
        return ares.findByIdentification(88241653).then(function(data) {
          expect(data.length).to.equal(1);
          expect(data.data[0].name).to.equal('David Kudera');
          expect(ares.lastOriginalData).not.to.be["null"];
          return done();
        }).done();
      });
      it('should load informations about some random companies', function(done) {
        return ares.findByCompanyName('EUROPA MÖBEL').then(function(data) {
          expect(data.length).to.be.above(1);
          expect(ares.lastOriginalData).not.to.be["null"];
          return done();
        }).done();
      });
      it('should return an error', function(done) {
        return ares.findByIdentification(12345678).fail(function(err) {
          expect(err).to.be.an["instanceof"](Error);
          return done();
        }).done();
      });
      return it.skip('should return an error from ares', function(done) {
        return ares.findByCompanyName('europa').fail(function(err) {
          expect(err).to.be.an["instanceof"](Error);
          return done();
        }).done();
      });
    });
  });

}).call(this);
