// Generated by CoffeeScript 1.6.3
(function() {
  var Ares, ares, should;

  should = require('should');

  Ares = require('../../lib/Ares');

  ares = new Ares;

  describe('Ares', function() {
    return describe('#findByIdentification()', function() {
      it('should load old information about author', function(done) {
        return ares.findByIdentification(88241653).then(function(data) {
          data.length.should.be.equal(1);
          data.data[0].name.should.be.equal('David Kudera');
          ares.lastOriginalData.should.not.be["null"];
          return done();
        }).done();
      });
      it('should load informations about some random companies', function(done) {
        return ares.findByCompanyName('EUROPA MÖBEL').then(function(data) {
          data.length.should.be.above(1);
          ares.lastOriginalData.should.not.be["null"];
          return done();
        }).done();
      });
      it('should return an error', function(done) {
        return ares.findByIdentification(12345678).fail(function(err) {
          err.should.be.an.instanceOf(Error);
          return done();
        }).done();
      });
      return it.skip('should return an error from ares', function(done) {
        return ares.findByCompanyName('europa').fail(function(err) {
          err.should.be.an.instanceOf(Error);
          return done();
        }).done();
      });
    });
  });

}).call(this);
