// Generated by CoffeeScript 1.6.3
(function() {
  var Validators, expect;

  expect = require('chai').expect;

  Validators = require('../../lib/Validators');

  describe('Validators', function() {
    return describe('#companyIdentification()', function() {
      it('should return true', function() {
        expect(Validators.companyIdentification('69663963')).to.be["true"];
        expect(Validators.companyIdentification('   69663963   ')).to.be["true"];
        expect(Validators.companyIdentification(69663963)).to.be["true"];
        return expect(Validators.companyIdentification(25596641)).to.be["true"];
      });
      return it('should return false', function() {
        expect(Validators.companyIdentification('---')).to.be["false"];
        return expect(Validators.companyIdentification('12345678')).to.be["false"];
      });
    });
  });

}).call(this);
