// Generated by CoffeeScript 1.6.3
(function() {
  var Url;

  Url = (function() {
    function Url() {}

    /*
       From http://www.navioo.com/javascript/tutorials/Javascript_urlencode_1542.html
    */


    Url.urlencode = function(param) {
      var histogram, replace, replacer, ret, search;
      histogram = {};
      ret = param.toString();
      replacer = function(search, replace, str) {
        var tmp_arr;
        tmp_arr = str.split(search);
        return tmp_arr.join(replace);
      };
      histogram["'"] = '%27';
      histogram['('] = '%28';
      histogram[')'] = '%29';
      histogram['*'] = '%2A';
      histogram['~'] = '%7E';
      histogram['!'] = '%21';
      histogram['%20'] = '+';
      ret = encodeURIComponent(ret);
      for (search in histogram) {
        replace = histogram[search];
        ret = replacer(search, replace, ret);
      }
      ret = ret.replace(/(\%([a-z0-9]{2}))/g, function(full, m1, m2) {
        return '%' + m2.toUpperCase();
      });
      return ret;
    };

    /*
       From http://www.navioo.com/javascript/tutorials/Javascript_http_build_query_1537.html
    */


    Url.buildQuery = function(params) {
      var key, result, value;
      result = [];
      for (key in params) {
        value = params[key];
        key = this.urlencode(key);
        value = this.urlencode(value.toString());
        result.push("" + key + "=" + value);
      }
      return result.join('&');
    };

    return Url;

  })();

  module.exports = Url;

}).call(this);
