module.exports = """
<?xml version="1.0" encoding="UTF-8"?>
<are:Ares_odpovedi xmlns:are="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer/v_1.0.1" xmlns:dtt="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.4" xmlns:udt="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1" odpoved_datum_cas="2013-12-08T21:45:44" odpoved_pocet="1" odpoved_typ="Standard" vystup_format="XML" xslt="klient" validation_XSLT="/ares/xml_doc/schemas/ares/ares_answer/v_1.0.0/ares_answer.xsl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer/v_1.0.1 http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer/v_1.0.1/ares_answer_v_1.0.1.xsd" Id="ares">
<are:Odpoved>
<are:Pocet_zaznamu>3</are:Pocet_zaznamu>
<are:Typ_vyhledani>OF</are:Typ_vyhledani>
<are:Zaznam>
<are:Shoda_OF>
<dtt:Kod>7</dtt:Kod>
</are:Shoda_OF>
<are:Vyhledano_dle>OF</are:Vyhledano_dle>
<are:Typ_registru>
<dtt:Kod>2</dtt:Kod>
<dtt:Text>OR</dtt:Text>
</are:Typ_registru>
<are:Datum_vzniku>1990-12-20</are:Datum_vzniku>
<are:Datum_platnosti>2013-12-08</are:Datum_platnosti>
<are:Pravni_forma>
<dtt:Kod_PF>112</dtt:Kod_PF>
</are:Pravni_forma>
<are:Obchodni_firma>IBM Česká republika, spol. s r.o.</are:Obchodni_firma>
<are:ICO>14890992</are:ICO>
<are:Identifikace>
<are:Adresa_ARES>
<dtt:ID_adresy>202869063</dtt:ID_adresy>
<dtt:Kod_statu>203</dtt:Kod_statu>
<dtt:Nazev_okresu>Hlavní město Praha</dtt:Nazev_okresu>
<dtt:Nazev_obce>Praha</dtt:Nazev_obce>
<dtt:Nazev_casti_obce>Chodov</dtt:Nazev_casti_obce>
<dtt:Nazev_mestske_casti>Praha 11</dtt:Nazev_mestske_casti>
<dtt:Nazev_ulice>V parku</dtt:Nazev_ulice>
<dtt:Cislo_domovni>2294</dtt:Cislo_domovni>
<dtt:Cislo_orientacni>4</dtt:Cislo_orientacni>
<dtt:PSC>14800</dtt:PSC>
<dtt:Adresa_UIR>
<udt:Kod_oblasti>19</udt:Kod_oblasti>
<udt:Kod_kraje>19</udt:Kod_kraje>
<udt:Kod_okresu>3100</udt:Kod_okresu>
<udt:Kod_obce>554782</udt:Kod_obce>
<udt:Kod_pobvod>43</udt:Kod_pobvod>
<udt:Kod_sobvod>116</udt:Kod_sobvod>
<udt:Kod_casti_obce>400211</udt:Kod_casti_obce>
<udt:Kod_mestske_casti>547034</udt:Kod_mestske_casti>
<udt:PSC>14800</udt:PSC>
<udt:Kod_ulice>721719</udt:Kod_ulice>
<udt:Cislo_domovni>2294</udt:Cislo_domovni>
<udt:Typ_cislo_domovni>1</udt:Typ_cislo_domovni>
<udt:Cislo_orientacni>4</udt:Cislo_orientacni>
<udt:Kod_adresy>25714023</udt:Kod_adresy>
<udt:Kod_objektu>25226509</udt:Kod_objektu>
</dtt:Adresa_UIR>
</are:Adresa_ARES>
</are:Identifikace>
<are:Kod_FU>13</are:Kod_FU>
<are:Priznaky_subjektu>NAAANANNNNNNNNNNNNNNNNNNANNNNN</are:Priznaky_subjektu>
</are:Zaznam>
<are:Zaznam>
<are:Shoda_OF>
<dtt:Kod>7</dtt:Kod>
</are:Shoda_OF>
<are:Vyhledano_dle>OF</are:Vyhledano_dle>
<are:Typ_registru>
<dtt:Kod>2</dtt:Kod>
<dtt:Text>OR</dtt:Text>
</are:Typ_registru>
<are:Datum_vzniku>2001-04-02</are:Datum_vzniku>
<are:Datum_platnosti>2013-12-08</are:Datum_platnosti>
<are:Pravni_forma>
<dtt:Kod_PF>112</dtt:Kod_PF>
</are:Pravni_forma>
<are:Obchodni_firma>IBM Global Services Delivery Center Czech Republic, s.r.o.</are:Obchodni_firma>
<are:ICO>26244535</are:ICO>
<are:Identifikace>
<are:Adresa_ARES>
<dtt:ID_adresy>202879318</dtt:ID_adresy>
<dtt:Kod_statu>203</dtt:Kod_statu>
<dtt:Nazev_okresu>Brno-město</dtt:Nazev_okresu>
<dtt:Nazev_obce>Brno</dtt:Nazev_obce>
<dtt:Nazev_casti_obce>Královo Pole</dtt:Nazev_casti_obce>
<dtt:Nazev_mestske_casti>Brno-Královo Pole</dtt:Nazev_mestske_casti>
<dtt:Nazev_ulice>Technická</dtt:Nazev_ulice>
<dtt:Cislo_domovni>2995</dtt:Cislo_domovni>
<dtt:Cislo_orientacni>21</dtt:Cislo_orientacni>
<dtt:PSC>61600</dtt:PSC>
<dtt:Adresa_UIR>
<udt:Kod_oblasti>60</udt:Kod_oblasti>
<udt:Kod_kraje>116</udt:Kod_kraje>
<udt:Kod_okresu>3702</udt:Kod_okresu>
<udt:Kod_obce>582786</udt:Kod_obce>
<udt:Kod_casti_obce>411965</udt:Kod_casti_obce>
<udt:Kod_mestske_casti>551007</udt:Kod_mestske_casti>
<udt:PSC>61600</udt:PSC>
<udt:Kod_ulice>36951</udt:Kod_ulice>
<udt:Cislo_domovni>2995</udt:Cislo_domovni>
<udt:Typ_cislo_domovni>1</udt:Typ_cislo_domovni>
<udt:Cislo_orientacni>21</udt:Cislo_orientacni>
<udt:Kod_adresy>26714361</udt:Kod_adresy>
<udt:Kod_objektu>26202018</udt:Kod_objektu>
</dtt:Adresa_UIR>
</are:Adresa_ARES>
</are:Identifikace>
<are:Kod_FU>13</are:Kod_FU>
<are:Priznaky_subjektu>NAAANANNNNANNNNNNNNNNNNNANNNNN</are:Priznaky_subjektu>
</are:Zaznam>
<are:Zaznam>
<are:Shoda_OF>
<dtt:Kod>7</dtt:Kod>
</are:Shoda_OF>
<are:Vyhledano_dle>OF</are:Vyhledano_dle>
<are:Typ_registru>
<dtt:Kod>4</dtt:Kod>
<dtt:Text>RŽP</dtt:Text>
</are:Typ_registru>
<are:Datum_vzniku>2002-05-13</are:Datum_vzniku>
<are:Datum_platnosti>2013-12-08</are:Datum_platnosti>
<are:Pravni_forma>
<dtt:Kod_PF>112</dtt:Kod_PF>
</are:Pravni_forma>
<are:Obchodni_firma>IBM Business Consulting Services s.r.o.</are:Obchodni_firma>
<are:ICO>26698153</are:ICO>
<are:Identifikace>
<are:Adresa_ARES>
<dtt:ID_adresy>400115370</dtt:ID_adresy>
<dtt:Kod_statu>203</dtt:Kod_statu>
<dtt:Nazev_okresu>Hlavní město Praha</dtt:Nazev_okresu>
<dtt:Nazev_obce>Praha</dtt:Nazev_obce>
<dtt:Nazev_casti_obce>Nové Město</dtt:Nazev_casti_obce>
<dtt:Nazev_mestske_casti>Praha 2</dtt:Nazev_mestske_casti>
<dtt:Nazev_ulice>Kateřinská</dtt:Nazev_ulice>
<dtt:Cislo_domovni>466</dtt:Cislo_domovni>
<dtt:Typ_cislo_domovni>1</dtt:Typ_cislo_domovni>
<dtt:Cislo_orientacni>40</dtt:Cislo_orientacni>
<dtt:PSC>12000</dtt:PSC>
<dtt:Adresa_UIR>
<udt:Kod_oblasti>19</udt:Kod_oblasti>
<udt:Kod_kraje>19</udt:Kod_kraje>
<udt:Kod_okresu>3100</udt:Kod_okresu>
<udt:Kod_obce>554782</udt:Kod_obce>
<udt:Kod_pobvod>27</udt:Kod_pobvod>
<udt:Kod_sobvod>27</udt:Kod_sobvod>
<udt:Kod_casti_obce>490148</udt:Kod_casti_obce>
<udt:Kod_mestske_casti>500089</udt:Kod_mestske_casti>
<udt:PSC>12000</udt:PSC>
<udt:Kod_ulice>451592</udt:Kod_ulice>
<udt:Cislo_domovni>466</udt:Cislo_domovni>
<udt:Typ_cislo_domovni>1</udt:Typ_cislo_domovni>
<udt:Cislo_orientacni>40</udt:Cislo_orientacni>
<udt:Kod_adresy>25326309</udt:Kod_adresy>
<udt:Kod_objektu>24857351</udt:Kod_objektu>
</dtt:Adresa_UIR>
</are:Adresa_ARES>
</are:Identifikace>
<are:Kod_FU>2</are:Kod_FU>
<are:Priznaky_subjektu>NZZANZNNNNNNNNNNNNNNNNNNZNNNNN</are:Priznaky_subjektu>
</are:Zaznam>
</are:Odpoved>
</are:Ares_odpovedi>

"""